# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAlerts < Formula
  desc "Tool to detect and monitor GitHub org users public repositories"
  homepage "https://github.com/boringtools/git-alerts"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boringtools/git-alerts/releases/download/v1.7.0/git-alerts_Darwin_x86_64.tar.gz"
      sha256 "bef55d332e24fb91be4634c9a004ac464ad06352ac07cdec34b23ac721bcdb20"

      def install
        bin.install "git-alerts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boringtools/git-alerts/releases/download/v1.7.0/git-alerts_Darwin_arm64.tar.gz"
      sha256 "56d59cb0d9fc02dc1484543f7ce25105bb4a0c4026ca0af752681cb0d46b0666"

      def install
        bin.install "git-alerts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boringtools/git-alerts/releases/download/v1.7.0/git-alerts_Linux_x86_64.tar.gz"
      sha256 "02945e68847cd75295f57eeb766114af3d7c879c00e2db6977a698d0dc54523d"
      def install
        bin.install "git-alerts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boringtools/git-alerts/releases/download/v1.7.0/git-alerts_Linux_arm64.tar.gz"
      sha256 "060345a131865a4b93ff6fe5768c0cc4c9c7c27e56b898a2ea24373b502bf10a"
      def install
        bin.install "git-alerts"
      end
    end
  end
end
