# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAlerts < Formula
  desc "Tool to detect and monitor GitHub org users public repositories"
  homepage "https://github.com/boringtools/git-alerts"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/boringtools/git-alerts/releases/download/v1.6.0/git-alerts_Darwin_x86_64.tar.gz"
      sha256 "b4e58e4c720d326bc6c9aada264423594d242c3207cfe826b90abab9bbcd6734"

      def install
        bin.install "git-alerts"
      end
    end
    on_arm do
      url "https://github.com/boringtools/git-alerts/releases/download/v1.6.0/git-alerts_Darwin_arm64.tar.gz"
      sha256 "82d8b6824b3414641761645d97551635eaddea8e3d77c02c8b6099aa55466d64"

      def install
        bin.install "git-alerts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boringtools/git-alerts/releases/download/v1.6.0/git-alerts_Linux_x86_64.tar.gz"
        sha256 "e999c22a9f68fe7eb4d76ad705799707c0e0853d7bc34e965515197de033dac7"

        def install
          bin.install "git-alerts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boringtools/git-alerts/releases/download/v1.6.0/git-alerts_Linux_arm64.tar.gz"
        sha256 "8f4179edfbcb98fe33a42a1706dd4009f3f03c5ddf2c9e790c7568e81630705e"

        def install
          bin.install "git-alerts"
        end
      end
    end
  end
end
