# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAlerts < Formula
  desc "Tool to detect and monitor GitHub org users public repositories"
  homepage "https://github.com/boringtools/git-alerts"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/boringtools/git-alerts/releases/download/v1.3.0/git-alerts_Darwin_x86_64.tar.gz"
      sha256 "5a947efbd8618ab23320bcce70994694457b390bf90cd8c1ceb5e146f86f68a2"

      def install
        bin.install "git-alerts"
      end
    end
    on_arm do
      url "https://github.com/boringtools/git-alerts/releases/download/v1.3.0/git-alerts_Darwin_arm64.tar.gz"
      sha256 "b8667b0819a946bdd18d598935eb39c076b5cbd928ca1ea1c419a0353b3a74be"

      def install
        bin.install "git-alerts"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boringtools/git-alerts/releases/download/v1.3.0/git-alerts_Linux_x86_64.tar.gz"
        sha256 "933e793c4b39b70dcdeca6245c192e0dc7a3c64e3f8fff4f36228bf505c727e1"

        def install
          bin.install "git-alerts"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/boringtools/git-alerts/releases/download/v1.3.0/git-alerts_Linux_arm64.tar.gz"
        sha256 "41e7ccd0e6769d85e2bac14567b1b3b12777a5d46244239d4e33db15d41618e2"

        def install
          bin.install "git-alerts"
        end
      end
    end
  end
end
